<a href="https://colab.research.google.com/github/Yash-k10/pattern_recognition/blob/main/Practical1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import euclidean_distances, manhattan_distances, cosine_similarity

In [10]:
df = pd.read_csv("customers.csv")   # change file name if needed
df.head()

   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185

In [11]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel           440 non-null    int64
 1   Region            440 non-null    int64
 2   Fresh             440 non-null    int64
 3   Milk              440 non-null    int64
 4   Grocery           440 non-null    int64
 5   Frozen            440 non-null    int64
 6   Detergents_Paper  440 non-null    int64
 7   Delicassen        440 non-null    int64
dtypes: int64(8)
memory usage: 27.6 KB
None
          Channel      Region          Fresh          Milk       Grocery  \
count  440.000000  440.000000     440.000000    440.000000    440.000000
mean     1.322727    2.543182   12000.297727   5796.265909   7951.277273
std      0.468052    0.774272   12647.328865   7380.377175   9503.162829
min      1.000000    1.000000       3.000000     55.000000      3.000000
25%      1.000000    2.000000    3127.750000   1533.000000   2153.000000
50%      1.000000    3.000000    8504.000000   3627.000000   4755.500000
75%      2.000000    3.000000   16933.750000   7190.250000  10655.750000
max      2.000000    3.000000  112151.000000  73498.000000  92780.000000

             Frozen  Detergents_Paper    Delicassen
count    440.000000        440.000000    440.000000
mean    3071.931818       2881.493182   1524.870455
std     4854.673333       4767.854448   2820.105937
min       25.000000          3.000000      3.000000
25%      742.250000        256.750000    408.250000
50%     1526.000000        816.500000    965.500000
75%     3554.250000       3922.000000   1820.250000
max    60869.000000      40827.000000  47943.000000

In [13]:
print(df.columns)

Index(['Channel', 'Region', 'Fresh', 'Milk', 'Grocery', 'Frozen',
       'Detergents_Paper', 'Delicassen'],
      dtype='object')

In [14]:
features = df[['Fresh', 'Milk', 'Grocery', 'Frozen', 'Detergents_Paper', 'Delicassen']].values

In [16]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import euclidean_distances, manhattan_distances, cosine_similarity

df = pd.read_csv("customers.csv")

df.columns = df.columns.str.strip()
df.head()

   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185

In [17]:
euclidean_dist = euclidean_distances(features)

euclidean_df = pd.DataFrame(euclidean_dist)
euclidean_df

,0,1,2,3,4,5,6,7,8,9,...,430,431,432,433,434,435,436,437,438,439
0,0.000000,6206.256360,9405.507429,11238.189578,12098.951194,4412.718437,6576.310136,7451.170579,9178.708515,14094.167730,...,14396.774569,14763.048127,12413.701261,14128.935239,7080.436004,23269.692692,29075.136388,26463.519248,10027.057794,13892.411418
1,6206.256360,0.000000,6506.372107,13062.954222,16899.207378,5589.145373,8905.393029,4948.484313,7476.070492,10345.210293,...,10268.949021,13466.030298,17425.370441,11966.513820,11559.225753,26434.612008,34652.672364,25508.355396,11660.790196,12150.499949
2,9405.507429,6506.372107,0.000000,13395.218363,16988.518064,7941.333389,11064.063133,6914.661886,9299.946236,13437.401386,...,12501.209621,13771.774686,18704.527607,11845.266692,13602.026687,27989.341793,35063.486877,28076.035030,11731.025360,12863.324493
3,11238.189578,13062.954222,13395.218363,0.000000,11549.478560,10011.995555,7514.343617,10222.735740,10074.915136,21000.574730,...,17236.104113,9635.630182,10108.999159,12752.374210,8410.078061,23937.534272,26270.771572,33527.352863,6515.014735,12496.620583
4,12098.951194,16899.207378,16988.518064,11549.478560,0.000000,14532.786037,12253.324651,15669.684394,17699.119470,22218.750370,...,22174.577110,17544.896523,7918.438040,22015.571557,8193.411377,16393.067193,18559.912931,29862.398916,14441.413781,21720.176357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,23269.692692,26434.612008,27989.341793,23937.534272,16393.067193,26524.326646,25315.975332,26922.799316,29948.899913,27685.876363,...,30447.129093,24721.393084,22124.420874,34535.981570,21458.518122,0.000000,22602.829557,28641.512931,28546.722054,34495.042876
436,29075.136388,34652.672364,35063.486877,26270.771572,18559.912931,31193.861864,28372.336157,33281.447309,34099.957009,39878.943642,...,39698.204090,32573.759408,19165.554753,37425.633796,24221.148239,22602.829557,0.000000,43713.553653,29188.604249,36827.085182
437,26463.519248,25508.355396,28076.035030,33527.352863,29862.398916,29660.405712,28928.641586,26968.827227,31073.465899,16633.051284,...,25691.261802,33413.546280,32910.408232,36685.168202,28111.440714,28641.512931,43713.553653,0.000000,34652.069852,36151.929824
438,10027.057794,11660.790196,11731.025360,6515.014735,14441.413781,7197.043699,6244.278741,8859.335923,6468.857395,20766.555323,...,16127.925285,13449.660665,11365.959484,8476.112493,9224.244359,28546.722054,29188.604249,34652.069852,0.000000,7860.783740
439,13892.411418,12150.499949,12863.324493,12496.620583,21720.176357,9891.894611,10812.631040,9919.185047,5440.452647,20501.104434,...,14358.984400,15413.112502,18498.518806,2852.637376,15298.651215,34495.042876,36827.085182,36151.929824,7860.783740,0.000000

In [18]:
manhattan_dist = manhattan_distances(features)

manhattan_df = pd.DataFrame(manhattan_dist)
manhattan_df

,0,1,2,3,4,5,6,7,8,9,...,430,431,432,433,434,435,436,437,438,439
0,0.0,10378.0,16826.0,21203.0,23000.0,8532.0,9111.0,14985.0,15840.0,25876.0,...,27456.0,25416.0,22093.0,26949.0,11506.0,44174.0,49466.0,43295.0,19500.0,26523.0
1,10378.0,0.0,10524.0,27609.0,29406.0,11268.0,16939.0,6429.0,14572.0,16704.0,...,20998.0,24106.0,32361.0,23227.0,20070.0,46258.0,55872.0,46791.0,22596.0,25677.0
2,16826.0,10524.0,0.0,31051.0,26054.0,16020.0,21691.0,13029.0,17916.0,24730.0,...,27502.0,27572.0,37113.0,26571.0,25442.0,54640.0,58198.0,56687.0,26650.0,29021.0
3,21203.0,27609.0,31051.0,0.0,23697.0,19183.0,15696.0,22978.0,19951.0,44289.0,...,31851.0,18223.0,16768.0,21386.0,18495.0,46571.0,32521.0,61960.0,11791.0,20796.0
4,23000.0,29406.0,26054.0,23697.0,0.0,25124.0,22361.0,24127.0,27406.0,45466.0,...,37964.0,29874.0,17075.0,36061.0,16336.0,36354.0,32144.0,61067.0,28266.0,38511.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,44174.0,46258.0,54640.0,46571.0,36354.0,49818.0,52753.0,50787.0,57676.0,46834.0,...,47626.0,40834.0,46569.0,63611.0,45136.0,0.0,44264.0,60519.0,55468.0,66303.0
436,49466.0,55872.0,58198.0,32521.0,32144.0,47446.0,43959.0,50125.0,48214.0,71932.0,...,58998.0,50274.0,29797.0,43891.0,39826.0,44264.0,0.0,87533.0,34724.0,45577.0
437,43295.0,46791.0,56687.0,61960.0,61067.0,51155.0,51028.0,51752.0,58713.0,32651.0,...,51403.0,67945.0,61554.0,69576.0,49765.0,60519.0,87533.0,0.0,61291.0,69818.0
438,19500.0,22596.0,26650.0,11791.0,28266.0,12722.0,12907.0,17105.0,13490.0,37450.0,...,24274.0,22494.0,17827.0,11651.0,17984.0,55468.0,34724.0,61291.0,0.0,11419.0
439,26523.0,25677.0,29021.0,20796.0,38511.0,19121.0,18876.0,21928.0,11105.0,39073.0,...,19589.0,27971.0,22508.0,6336.0,24955.0,66303.0,45577.0,69818.0,11419.0,0.0

In [19]:
cos_sim = cosine_similarity(features)

cosine_df = pd.DataFrame(cos_sim)
cosine_df

,0,1,2,3,4,5,6,7,8,9,...,430,431,432,433,434,435,436,437,438,439
0,1.000000,0.939031,0.851704,0.782379,0.898106,0.995305,0.936995,0.921029,0.957496,0.812390,...,0.667947,0.657147,0.820631,0.860163,0.929012,0.906807,0.735686,0.847835,0.865589,0.971631
1,0.939031,1.000000,0.917220,0.655127,0.752968,0.939980,0.834395,0.954797,0.951988,0.944936,...,0.814379,0.686067,0.609968,0.904141,0.797667,0.833942,0.491608,0.937962,0.682742,0.938949
2,0.851704,0.917220,1.000000,0.638859,0.748767,0.868563,0.743894,0.902934,0.854618,0.848270,...,0.723775,0.672264,0.544054,0.933671,0.713964,0.763270,0.468692,0.828192,0.681052,0.815950
3,0.782379,0.655127,0.638859,1.000000,0.951613,0.771529,0.877320,0.762316,0.775975,0.504615,...,0.456648,0.840770,0.905977,0.689964,0.903088,0.953236,0.911114,0.571245,0.934889,0.784478
4,0.898106,0.752968,0.748767,0.951613,1.000000,0.886721,0.947686,0.835431,0.862829,0.594238,...,0.511110,0.719504,0.954238,0.751016,0.969354,0.948047,0.930474,0.663240,0.991801,0.875383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,0.906807,0.833942,0.763270,0.953236,0.948047,0.901265,0.922250,0.877738,0.899478,0.692689,...,0.629140,0.858407,0.869426,0.825810,0.934659,1.000000,0.831845,0.731801,0.914421,0.911873
436,0.735686,0.491608,0.468692,0.911114,0.930474,0.719697,0.840379,0.594448,0.656275,0.291138,...,0.213915,0.584251,0.972037,0.516060,0.889006,0.831845,1.000000,0.394712,0.961916,0.695449
437,0.847835,0.937962,0.828192,0.571245,0.663240,0.820122,0.826286,0.955370,0.940425,0.986872,...,0.887339,0.556757,0.564833,0.723007,0.763903,0.731801,0.394712,1.000000,0.581994,0.907013
438,0.865589,0.682742,0.681052,0.934889,0.991801,0.853691,0.922405,0.768274,0.809905,0.504148,...,0.429167,0.654602,0.971396,0.690981,0.955864,0.914421,0.961916,0.581994,1.000000,0.833213
439,0.971631,0.938949,0.815950,0.784478,0.875383,0.949599,0.956072,0.959770,0.992860,0.870975,...,0.794935,0.647442,0.815430,0.791703,0.940284,0.911873,0.695449,0.907013,0.833213,1.000000

In [21]:
df.index = [f"C{i}" for i in range(len(df))]
cosine_df.index = df.index
cosine_df.columns = df.index
cosine_df

,C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C430,C431,C432,C433,C434,C435,C436,C437,C438,C439
C0,1.000000,0.939031,0.851704,0.782379,0.898106,0.995305,0.936995,0.921029,0.957496,0.812390,...,0.667947,0.657147,0.820631,0.860163,0.929012,0.906807,0.735686,0.847835,0.865589,0.971631
C1,0.939031,1.000000,0.917220,0.655127,0.752968,0.939980,0.834395,0.954797,0.951988,0.944936,...,0.814379,0.686067,0.609968,0.904141,0.797667,0.833942,0.491608,0.937962,0.682742,0.938949
C2,0.851704,0.917220,1.000000,0.638859,0.748767,0.868563,0.743894,0.902934,0.854618,0.848270,...,0.723775,0.672264,0.544054,0.933671,0.713964,0.763270,0.468692,0.828192,0.681052,0.815950
C3,0.782379,0.655127,0.638859,1.000000,0.951613,0.771529,0.877320,0.762316,0.775975,0.504615,...,0.456648,0.840770,0.905977,0.689964,0.903088,0.953236,0.911114,0.571245,0.934889,0.784478
C4,0.898106,0.752968,0.748767,0.951613,1.000000,0.886721,0.947686,0.835431,0.862829,0.594238,...,0.511110,0.719504,0.954238,0.751016,0.969354,0.948047,0.930474,0.663240,0.991801,0.875383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C435,0.906807,0.833942,0.763270,0.953236,0.948047,0.901265,0.922250,0.877738,0.899478,0.692689,...,0.629140,0.858407,0.869426,0.825810,0.934659,1.000000,0.831845,0.731801,0.914421,0.911873
C436,0.735686,0.491608,0.468692,0.911114,0.930474,0.719697,0.840379,0.594448,0.656275,0.291138,...,0.213915,0.584251,0.972037,0.516060,0.889006,0.831845,1.000000,0.394712,0.961916,0.695449
C437,0.847835,0.937962,0.828192,0.571245,0.663240,0.820122,0.826286,0.955370,0.940425,0.986872,...,0.887339,0.556757,0.564833,0.723007,0.763903,0.731801,0.394712,1.000000,0.581994,0.907013
C438,0.865589,0.682742,0.681052,0.934889,0.991801,0.853691,0.922405,0.768274,0.809905,0.504148,...,0.429167,0.654602,0.971396,0.690981,0.955864,0.914421,0.961916,0.581994,1.000000,0.833213
C439,0.971631,0.938949,0.815950,0.784478,0.875383,0.949599,0.956072,0.959770,0.992860,0.870975,...,0.794935,0.647442,0.815430,0.791703,0.940284,0.911873,0.695449,0.907013,0.833213,1.000000

In [23]:
def most_similar(customer, matrix):
    idx = df.index.get_loc(customer)
    scores = matrix[idx]

    sorted_idx = np.argsort(scores)[::-1]

    for i in sorted_idx:
        if i != idx:
            return df.index[i]

print("Most similar to C0:", most_similar("C0", cos_sim))

Most similar to C0: C5